name: Helm Charts
 
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Microservice Chart
        run: | 
          echo ${{ secrets.GIT_PAT }} | docker login ghcr.io -u argo-universe --password-stdin
          export CHART_VERSION=$(grep 'version:' ./path/to/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push microservice-${CHART_VERSION}.tgz oci://ghcr.io/argo-universe